### ISSUE TITLE
Swap out jsonwebtoken for iron module?

### ISSUE THREAD

**Issue by nelsonic** [ideaq/hapi-auth-jwt2#27]
in https://github.com/ideaq/hapi-auth-jwt2/issues/25 @poeticninja mentioned switching from [**jsonwebtoken**](https://www.npmjs.com/package/jsonwebtoken) to [***iron***](https://www.npmjs.com/package/iron) for the JSON token encryption.

While we ***love*** the work @hueniverse & Co. are doing with **iron** (and ***trust*** him on **security** matters), we like the fact **jwt** has a [**Spec**](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32) which means if people want to use multiple backends (e.g. Node/Scala/Go/Erlang) there are *already* [modules](https://developer.atlassian.com/static/connect/docs/latest/concepts/understanding-jwt.html#libraries) they can use to sign/decode JWTs ... also the fact that [**Auth0**](https://auth0.com/why-auth0) are *invested* in maintaining the **node-jsonwebtoken** module gives us (*some*) assurance that our backs are covered...

We are torn. :confused:

@evilpacket what are the fine folks [**@liftsecurity**](https://twitter.com/liftsecurity) recommending for people building Hapi Apps/APIs who *can't* (or don't *want* to) use a 3rd Party/SASS Authentication Service? 

#**discuss** (*thanks*!)

**Comment by poeticninja** [comment]
@nelsonic Sorry. You miss understood me in the issue (https://github.com/ideaq/hapi-auth-jwt2/issues/25). For this plugin I would be using jsonwebtoken. I was just trying to point out how they use iron and this plugin uses jsonwebtoken and that should be the main difference.

The reason why people are going to want to use this plugin in Hapi is because they want jsonwebtokens in there application.

Sorry for the confusion.

**Comment by nelsonic** [comment]
Gotcha! :+1:

**Comment by poeticninja** [comment]
:smile:

**Comment by nelsonic** [comment]
Cool. Glad we're on the same page. Closing this. :+1:
